#!/usr/bin/env php
<?php
if (file_exists(__DIR__ . '../.env')) {
    include_once __DIR__ . '../.env';
}

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

if(YII_DEBUG) {
    error_reporting(E_ALL);
}

require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
